version: '3.9'

services:

  aeschain1:
    image: aeslabs/aeschain:latest
    ports:
      - 26656:26656
      - 26657:26657
      - 9090:9090
      - 4500:4500
    restart: always
    environment: 
      MONIKER: MY-AES-NODE-NAME-1
    volumes: 
      - aesdata1:/aeschain

  # aeschain2:
  #   build: .
  #   ports:
  #     - 36656:26656
  #     - 36657:26657
  #     - 9091:9090
  #     - 4501:4500
  #   restart: always
  #   environment: 
  #     MONIKER: MY-AES-NODE-NAME-2
  #   volumes: 
  #     - aesdata2:/aeschain

  # aeschain3:
  #   build: .
  #   ports:
  #     - 46656:26656
  #     - 46657:26657
  #     - 9092:9090
  #     - 4502:4500
  #   restart: always
  #   environment: 
  #     MONIKER: MY-AES-NODE-NAME-3
  #   volumes: 
  #     - aesdata3:/aeschain

volumes:
  aesdata1:
    driver: local
    driver_opts: 
      type: 'none'
      o: 'bind'
      device: './.aesdata1'
  # aesdata2:
  #   driver: local
  #   driver_opts: 
  #     type: 'none'
  #     o: 'bind'
  #     device: './.aesdata2'
  # aesdata3:
  #   driver: local
  #   driver_opts: 
  #     type: 'none'
  #     o: 'bind'
  #     device: './.aesdata3'

