version: '3.9'

services:

  aeschain1:
    image: aeslabs/aeschain:latest
    ports:
      - 26656:26656
      - 26657:26657
      - 9090:9090
      - 4500:4500
    restart: always
    environment: 
      CHAIN_ID: "aeternalism"
      MONIKER: "MY-AES-NODE-NAME-1"
      APP_HOME: "/aeschain/.aeschain"
      SEEDS_URL: "https://raw.githubusercontent.com/aeternalism/aeschain-version/main/oxygen/seeds"
      GENESIS_URL: "https://raw.githubusercontent.com/aeternalism/aeschain-version/main/oxygen/genesis.json"
    volumes: 
      - aesdata1:/aeschain

volumes:
  aesdata1:
    driver: local
    driver_opts: 
      type: 'none'
      o: 'bind'
      device: './.aesdata1'
